controllers/blockpy.py
from datetime import datetime, timedelta
import time
import os
import json
import json
import logging
from pprint import pprint

from slugify import slugify
from natsort import natsorted

from flask_wtf import Form
from wtforms import IntegerField, BooleanField

from flask import Blueprint, send_from_directory
from flask import Flask, redirect, url_for, session, request, jsonify, g,\
                  make_response, Response, render_template
from werkzeug.utils import secure_filename
                  
from sqlalchemy import Date, cast, func, desc, or_

from main import app

from models.models import (db, Assignment, User, Submission, Log,
                           AssignmentGroup)

from controllers.helpers import (lti, get_assignments_from_request, 
                                 highlight_python_code, normalize_url,
                                 ensure_dirs)

blueprint_blockpy = Blueprint('blockpy', __name__, url_prefix='/blockpy')

def failure(message):
    return jsonify(success=False, message=message, ip=request.remote_addr)
                           
@blueprint_blockpy.route('/static/<path:path>', methods=['GET', 'POST'])
def blockpy_static(path):
    return app.send_static_file(path)

@blueprint_blockpy.route('/', methods=['GET', 'POST'])    
@blueprint_blockpy.route('/index', methods=['GET', 'POST'])
@blueprint_blockpy.route('/index/', methods=['GET', 'POST'])
def index():
    return render_template('blockpy/index.html')

@blueprint_blockpy.route('/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/load', methods=['GET', 'POST'])
def load(lti=None, assignments=None, submissions=None, embed=False):
    """
    
    """
    if "embed" in request.args:
        embed = request.args.get("embed")
    if assignments is None or submissions is None:
        assignments, submissions = get_assignments_from_request()
    if "assignment_group_id" in request.args:
        group_id = int(request.args.get("assignment_group_id"))
    else:
        group_id = None
    if "assignment_id" in request.args:
        assignment_id = request.args.get("assignment_id")
    elif assignments:
        assignment_id = assignments[0].id
    else:
        assignment_id = None
    if assignments:
        if submissions:
            course_id = submissions[0].course_id
        else:
            course_id = assignments[0].course_id
        if g.user and g.user is not None:
            instructor_mode = g.user.is_instructor(course_id)
        else:
            instructor_mode = False
        if 'course_id' in request.values:
            course_id = int(request.values.get('course_id'))
    else:
        instructor_mode = False
        if 'course_id' in request.values:
            course_id = int(request.values.get('course_id'))
        else:
            course_id = None
    group = list(zip(assignments, submissions))
    
    return render_template('blockpy/blockpy.html',
                           group=group,
                           group_id=group_id,
                           course_id=course_id,
                           user_id=g.user.id if g.user is not None else -1,
                           embed=embed,
                           ip=request.remote_addr,
                           assignment_id=assignment_id,
                           instructor_mode=instructor_mode)
                           
@blueprint_blockpy.route('/load_assignment_give_feedback/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/load_assignment_give_feedback', methods=['GET', 'POST'])
def load_assignment_give_feedback():
    assignment_id = request.values.get('assignment_id', None)
    if assignment_id is None:
        return failure("No Assignment ID given!")
    assignment = Assignment.by_id(assignment_id)
    return jsonify(success=True, give_feedback=assignment.give_feedback)
                           
@blueprint_blockpy.route('/load_assignment/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/load_assignment', methods=['GET', 'POST'])
def load_assignment(lti=lti):
    assignment_id = request.values.get('assignment_id', None)
    group_id = request.values.get('group_id', None)
    course_id = request.values.get('course_id',  g.course.id if 'course' in g else None)
    if None in (assignment_id, course_id) or course_id == "":
        return failure("No Assignment ID or Course ID given!")
    timestamp = request.values.get('timestamp', '')
    user_id = g.user.id if g.user != None else -1
    assignment = Assignment.by_id(assignment_id)
    if user_id != -1:
        submission = assignment.get_submission(user_id, course_id=course_id)
        submission_status = submission.status
        submission_course_id = submission.course_id
        submission_code = submission.code
        log = Log.new('editor', 'load', assignment_id, user_id, 
                      body=str(assignment.version), timestamp=timestamp)
    else:
        submission_status = 0
        submission_course_id = course_id
        submission_code = assignment.starting_code or ""
    interface = ('Text' if assignment.mode.lower() == 'text' else 
                 'Split' if assignment.mode.lower() == 'split' else
                 'Upload' if assignment.mode.lower() == 'upload' else
                 'Blocks')
    upload = assignment.mode.lower() == 'upload'
    if assignment.settings:
        settings = json.loads(assignment.settings)
    else:
        settings = {}
    files = settings['files'] if 'files' in settings else []
    files = [f for f in files if f.strip()]
    added_modules = settings['modules']['added'] if 'modules' in settings else []
    removed_modules = settings['modules']['removed'] if 'modules' in settings else []
    return jsonify(success=True,
                   ip=request.remote_addr,
                   settings = {
                        'editor': interface,
                        'read_only': upload,
                        'status': submission_status
                    },
                   assignment = {
                        'assignment_id': assignment.id,
                        'course_id': course_id if course_id != None else submission_course_id,
                        'student_id': user_id,
                        'group_id': group_id,
                        'introduction': assignment.body,
                        'name': assignment.name,
                        'upload': upload,
                        'version': assignment.version,
                        'initial_view': interface,
                        'give_feedback': assignment.give_feedback,
                        'parsons': assignment.mode == 'parsons', 
                        'starting_code': assignment.starting_code,
                        'on_change': assignment.on_step,
                        'importable': settings.get('importable', False),
                        'secret': settings.get('secret', False),
                        'disable_algorithm_errors': settings.get('disable_algorithm_errors', False),
                        'disable_timeout': settings.get('disable_timeout', False),
                        'files': files,
                        'modules': {
                            'added': added_modules,
                            'removed': removed_modules,
                        },
                    },
                    programs = {
                        '__main__': submission_code,
                        'starting_code': assignment.starting_code,
                        'give_feedback': assignment.give_feedback,
                        'on_change': assignment.on_step
                    })

@blueprint_blockpy.route('/save_code/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/save_code', methods=['GET', 'POST'])
def save_code(lti=lti):
    assignment_id = request.values.get('assignment_id', None)
    assignment_version = int(request.values.get('version', -1))
    course_id = request.values.get('course_id',  g.course.id if 'course' in g else None)
    if None in (assignment_id, course_id) or course_id == "":
        return failure("No Assignment ID or Course ID given!")
    code = request.values.get('code', '')
    timestamp = request.values.get('timestamp', '')
    filename = request.values.get('filename', '__main__')
    is_version_correct = True
    if filename == "__main__":
        submission, is_version_correct = Submission.save_code(g.user.id, assignment_id, int(course_id), code, assignment_version, timestamp=timestamp)
    elif g.user.is_instructor(int(course_id)):
        if filename == "give_feedback":
            Assignment.edit(assignment_id=assignment_id, give_feedback=code)
        elif filename == "on_change":
            Assignment.edit(assignment_id=assignment_id, on_step=code)
        elif filename == "starting_code":
            Assignment.edit(assignment_id=assignment_id, starting_code=code)
        log = Log.new('instructor', filename, assignment_id, g.user.id, body=code, timestamp=timestamp)
    return jsonify(success=True, 
                   is_version_correct=is_version_correct, 
                   ip=request.remote_addr)
    
@blueprint_blockpy.route('/save_events/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/save_events', methods=['GET', 'POST'])
def save_events(lti=lti):
    assignment_id = request.values.get('assignment_id', None)
    event = request.values.get('event', "blank")
    action = request.values.get('action', "missing")
    body = request.values.get('body', "")
    timestamp = request.values.get('timestamp', "")
    user_id = g.user.id if g.user != None else -1
    if assignment_id is None:
        return failure("No Assignment ID given!")
    log = Log.new(event, action, assignment_id, user_id, body=body, timestamp=timestamp)
    return jsonify(success=True, 
                   ip=request.remote_addr)
                   
def get_group_score(group_id, user_id, course_id, hide_correctness):
    group = AssignmentGroup.by_id(group_id)

templates/blockpy/blockpy.html
{% set reduced_layout = embed or 'iframe' == request.form.get('launch_presentation_document_target') %}
{% extends 'layout.html' %}

{% from 'utilities/assignment_groups.html' import assignment_group_header %}

{% block title %}
BlockPy
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}

{% assets "blockpy_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% assets "blockpy_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}" />
{% endassets %}

<style>
.embedded-data {
    display: none;
}
.correct-submission {
    background-color: #ded;
}
.incorrect-submission {
    background-color: #edd;
}
.secret-submission {
    background-color: #dde;
}
</style>

{% endblock %}

{% block body %}

<span class='delete-on-load'>Loading! Please wait.</span>

{% if group and group|length > 1 %}
{{ assignment_group_header(group, assignment_id, embed, 'blockpy.load') }}
<script>
    $(document).ready(function() {
        loadNavigation();
    });
</script>
{% else %}
<script>
function markCorrect(args) {}
</script>
{% endif %}

<script>
function getQueryParams(){
    try{
        url = window.location.href;
        query_str = url.substr(url.indexOf('?')+1, url.length-1);
        r_params = query_str.split('&');
        params = {}
        for( i in r_params){
            param = r_params[i].split('=');
            params[ param[0] ] = param[1];
        }
        return params;
    }
    catch(e){
       return {};
    }
}
queryParams = getQueryParams();
DEFAULT_ASSIGNMENT = {
    'settings': {
        'editor': 'Blocks',
        'presentation_mode': (queryParams.presentation == "true"),
    },
    'assignment': {
        'introduction': "Welcome to BlockPy. Try running the code below.",
        'name': "Scratch Canvas",
        'give_feedback': decodeURIComponent(queryParams.give_feedback || ""),
        'starting_code': decodeURIComponent(queryParams.starting_code || ""),
        'on_change': decodeURIComponent(queryParams.on_change || ""),
        'initial_view': queryParams.view || "Blocks",
        'disable_algorithm_errors': false,
        "importable": true,
        'modules': {
            'added': ['Input','Conversion']
        },
        'files': []
    },
    'programs': {
        '__main__': decodeURIComponent(queryParams.code || "")
        //$("#default-body").html()
    }
}
</script>


<!-- Main BlockPy canvas -->
<div id="blockpy-div" style='height:100%'></div>

<script>
$(document).ready(function() {
    blockpy = new BlockPy({
        'blocklyPath': {{ url_for('static', filename='blockly/')|tojson }},
        'attachmentPoint': document.getElementById('blockpy-div'),
        'presentation_mode': (queryParams.presentation == "true"),
    {% if not group %}
        'instructor': (queryParams.mode == "instructor"),
        'disable_algorithm_errors': (queryParams.algorithm_errors == "true"),
        'disable_timeout_errors': (queryParams.timeout_errors == "true"),
        'disable_typed_blocks': (queryParams.typed_blocks == "true"),
        'editor': 'Split',
        'urls': {
            'import_datasets': {{ url_for('blockpy.load_corgis',path='')|tojson }},
            'load_file': {{ url_for('blockpy.load_file')|tojson }},
        }
    {% else %}
        'instructor': {{ 'true' if instructor_mode else 'false'}},
        'completedCallback': function(data) { markCorrect(data.assignment_id) },
        'urls': {
            {% if g.user != None %}
            'save_code': {{ url_for('blockpy.save_code')|tojson }},
            'log_event': {{ url_for('blockpy.save_events')|tojson }},
            'save_assignment': {{ url_for('blockpy.save_presentation')|tojson }},
            'save_success': {{ url_for('blockpy.save_correct')|tojson }},
            'get_history': {{ url_for('blockpy.get_history')|tojson }},
            {% endif %}
            'load_assignment': {{ url_for('blockpy.load_assignment')|tojson }},
            'import_datasets': {{ url_for('blockpy.load_corgis',path='')|tojson }},
            'load_file': {{ url_for('blockpy.load_file')|tojson }},
        }
    {% endif %}
    });
    blockpy.setUserData(
        {{ g.user.id|tojson if g.user != None else -1}},
        {{ course_id|tojson if course_id != None else -1 }},
        {{ group_id|tojson}}
        );
    var server = blockpy.components.server;
    {% if not group %}
    blockpy.setAssignment(DEFAULT_ASSIGNMENT.settings, DEFAULT_ASSIGNMENT.assignment, DEFAULT_ASSIGNMENT.programs);
    {% elif group and request.args.get("assignment_id") == None %}
    server.loadAssignment({{ group[0][0].id }});
    {% else %}
    server.loadAssignment({{ request.args.get("assignment_id")|int}});
    {% endif %}
    altAssignmentChangingFunction = server.loadAssignment.bind(server);
});

</script>

<script>
$(document).ready(function() {
    $('.delete-on-load').remove();
});
</script>

{% endblock %}

templates/blockpy/browse_submissions.html
{% set reduced_layout = embed or 'iframe' == request.form.get('launch_presentation_document_target') %}
{% extends 'layout.html' %}

{% block title %}
Browse Submissions
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block body %}

<script>

$(document).ready(function() {
});

</script>

<div class="alert alert-danger" id='error-box' role="alert" style="display:none"></div>

<h2>{{ submissions[0][2].title() }}</h2>
Assignment ID: {{ submissions[0][2].id }}<br>
Introduction: {{ submissions[0][2].body|safe }}<br>

{% for submission, user, assignment in submissions %}
<div class='row'>

<div class='col-md-12'>
<h3>{{ user.name() }}</h1>
User Email: {{ user.email }}<br>
User ID: {{ user.id }}<br>
Started: {{ submission.date_created.strftime("%I:%M:%S %p on %b %d, %Y") }}<br>
Last Modified: {{ submission.date_modified.strftime("%I:%M:%S %p on %b %d, %Y") }}<br>
Touches: {{ submission.version }}<br>
Estimated Time Spent: {{ submission.history|round(2) }} minutes<br>
Correct: {{ submission.correct }}<br>
{{ submission.highlighted_code|safe }}<br>
</div>


</div>
{% endfor %}

{% endblock %}

templates/blockpy/index.html
{% extends 'layout.html' %}

{% block title %}
BlockPy
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script type='text/javascript'>
</script>
<style>
.videoWrapper {
	position: relative;
	padding-bottom: 56.25%; /* 16:9 */
	padding-top: 25px;
	height: 0;
}
.videoWrapper iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}
</style>

<meta property="og:description" content="BlockPy is a web-based Python environment that lets you work with blocks, text, or both. Designed for Data Science and equipped with powerful tools like the State Explorer and Guided Feedback, the goal of BlockPy is to let you solve authentic, real-world problems." />
{% endblock %}

{% block body %}
    <div class="jumbotron" style='padding-top: 20px; padding-bottom: 20px'>
        <div class="container">
            <div class='row'>
                <div class='col-md-6'>
                    <h1>BlockPy</h1>
                    <p>BlockPy is a web-based Python environment that lets you work with blocks, text, or both. Designed for Data Science, equipped with powerful tools like the State Explorer, and scaffolding beginners with Guided Feedback, the goal of BlockPy is to let you authentically solve real-world problems.</p>
                    <p><a class="btn btn-primary btn-lg" href="{{ url_for('blockpy.load') }}" role="button">Try BlockPy Now &raquo;</a></p>
                </div>
                
                <div class='col-md-6'>
                <br></br>
                    <div class="videoWrapper">
                    <iframe width="560" height="349"
                            src="https://www.youtube.com/embed/0Q92VJMlf_0?cc_load_policy=1"
                            title="Youtube Video demoing various BlockPy features"
                            allowfullscreen></iframe>
                    </div>
                    <!--<img src='{{ url_for("static", filename="images/blockly-corgi-logo-large.png") }}' />-->
                </div>
            </div>
        </div>
    </div>
    
    <div class="container">
        <div class='row'>
            <div class='col-md-4'>
                <h2>For Instructors</h2>
                <p>Interested in making BlockPy problems for your class?</p>
                <ul>
                <li><a href="{{ url_for('blockpy.load', mode='instructor') }}">Try building problems now!</a></li>
                <li><a href="https://canvas.instructure.com/courses/1134562">See some sample problems!</a></li>
                <!--<li><a href="https://virginiatech.qualtrics.com/SE/?SID=SV_0UMPv09Ci7gdRCB">Take our survey!</a></li>-->
                </ul>
                <p>Interested in using BlockPy in your course? Check out our <a href='https://groups.google.com/forum/#!forum/blockpy'>Community</a>
                or get in touch with <a href='mailto:acbart@udel.edu'>acbart@udel.edu</a></p>
                <!--<p>Embed BlockPy (<a href="/tool_config.xml">LTI Configuration</a>)</p>-->
            </div>
            
            <div class='col-md-4'>
                <h2>For Developers</h2>
                <p>BlockPy is open-source!</p>
                <ul>
                <li><a href="https://github.com/RealTimeWeb/blockpy">Check out our source code!</a></li>
                <li><a href="https://github.com/RealTimeWeb/blockpy/issues">Report an issue!</a></li>
                <li><a href="https://github.com/RealTimeWeb/blockpy/pulls">Submit a Pull Request!</a></li>
                </ul>
                <p>Have some ideas for the future of BlockPy? Check out our <a href='https://groups.google.com/forum/#!forum/blockpy'>Community</a>
                or get in touch with <a href='mailto:acbart@udel.edu'>acbart@udel.edu</a></p>
            </div>
            
            <div class='col-md-4'>
                <h2>For Researchers</h2>
                <p>BlockPy is developed by <a href='https://acbart.com'>Austin Cory Bart</a>, Luke Gusukuma, and Dennis Kafura.</p>
                
                <p>Interested in this project as it develops? Check out our <a href='https://groups.google.com/forum/#!forum/blockpy'>Community</a>
                or get in touch with <a href='mailto:acbart@udel.edu'>acbart@udel.edu</a></p>
            </div>
            
            
        </div>
    </div>
{% endblock %}

templates/blockpy/regenerate.html
{% set reduced_layout = embed or 'iframe' == request.form.get('launch_presentation_document_target') %}
{% extends 'layout.html' %}

{% block title %}
Assignment
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}

{% assets "blockpy_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% assets "blockpy_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}" />
{% endassets %}

<style>
.embedded-data {
    display: none;
}
</style>

{% endblock %}

{% block body %}

<div id="blockpy-div" style='height:100%'></div>

<div>
</div>

<span class='delete-on-load'>Loading! Please wait.</span>

<script>
    $(document).ready(function() {
        queryParams = getQueryParams();
        blockpy = new BlockPy(
            // settings
            {
                'editor': 'Blocks',
                'blocklyPath': {{ url_for('static', filename='blockly/')|tojson }},
                'attachmentPoint': document.getElementById('blockpy-div'),
                'instructor': (queryParams.mode == "instructor"),
                'urls': {
                    'import_datasets': {{ url_for('blockpy.load_corgis',path='')|tojson }},
                    'walk_old_code': {{ url_for('blockpy.regenerate_walk',path='')|tojson }},
                    'log_event': {{ url_for('blockpy.regenerate_events',path='')|tojson }},
                }
            },
            // assignment
            {
                'introduction': "Welcome to BlockPy. Try running the code below.",
                'name': "Scratch Canvas",
                'give_feedback': '',
                'starting_code': 'x = 0',
                'initial_view': 'Blocks',
                'disable_algorithm_errors': false,
                "importable": true,
                'modules': {"removed": [], "added": ["Data - Publishers", "Data - Weather", "Data - Earthquakes", "Data - Parking", "Data - Classics", "Data - Tate", "Data - Broadway", "Data - School Scores"]}
            },
            // submission
            {},
            // programs
            {
                '__main__': "x = 0\nprint(x)"
                //$("#default-body").html()
            }
        )
    });
</script>

<script>
$(document).ready(function() {
    $('.delete-on-load').remove();
});

function getQueryParams(){
    try{
        url = window.location.href;
        query_str = url.substr(url.indexOf('?')+1, url.length-1);
        r_params = query_str.split('&');
        params = {}
        for( i in r_params){
            param = r_params[i].split('=');
            params[ param[0] ] = param[1];
        }
        return params;
    }
    catch(e){
       return {};
    }
}
</script>

{% endblock %}