controllers/blockpy.py
from datetime import datetime, timedelta
import time
import os
import json
import json
import logging
from pprint import pprint

from slugify import slugify
from natsort import natsorted

from flask_wtf import Form
from wtforms import IntegerField, BooleanField

from flask import Blueprint, send_from_directory
from flask import Flask, redirect, url_for, session, request, jsonify, g,\
                  make_response, Response, render_template
from werkzeug.utils import secure_filename
                  
from sqlalchemy import Date, cast, func, desc, or_

from main import app

from models.models import (db, Assignment, User, Submission, Log,
                           AssignmentGroup)

from controllers.helpers import (lti, get_assignments_from_request, 
                                 highlight_python_code, normalize_url,
                                 ensure_dirs)

blueprint_blockpy = Blueprint('blockpy', __name__, url_prefix='/blockpy')

def failure(message):
    return jsonify(success=False, message=message, ip=request.remote_addr)
                           
@blueprint_blockpy.route('/static/<path:path>', methods=['GET', 'POST'])
def blockpy_static(path):
    return app.send_static_file(path)

@blueprint_blockpy.route('/', methods=['GET', 'POST'])    
@blueprint_blockpy.route('/index', methods=['GET', 'POST'])
@blueprint_blockpy.route('/index/', methods=['GET', 'POST'])
def index():
    return render_template('blockpy/index.html')

@blueprint_blockpy.route('/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/load', methods=['GET', 'POST'])
def load(lti=None, assignments=None, submissions=None, embed=False):
    """
    
    """
    if "embed" in request.args:
        embed = request.args.get("embed")
    if assignments is None or submissions is None:
        assignments, submissions = get_assignments_from_request()
    if "assignment_group_id" in request.args:
        group_id = int(request.args.get("assignment_group_id"))
    else:
        group_id = None
    if "assignment_id" in request.args:
        assignment_id = request.args.get("assignment_id")
    elif assignments:
        assignment_id = assignments[0].id
    else:
        assignment_id = None
    if assignments:
        if submissions:
            course_id = submissions[0].course_id
        else:
            course_id = assignments[0].course_id
        if g.user and g.user is not None:
            instructor_mode = g.user.is_instructor(course_id)
        else:
            instructor_mode = False
        if 'course_id' in request.values:
            course_id = int(request.values.get('course_id'))
    else:
        instructor_mode = False
        if 'course_id' in request.values:
            course_id = int(request.values.get('course_id'))
        else:
            course_id = None
    group = list(zip(assignments, submissions))
    
    return render_template('blockpy/blockpy.html',
                           group=group,
                           group_id=group_id,
                           course_id=course_id,
                           user_id=g.user.id if g.user is not None else -1,
                           embed=embed,
                           ip=request.remote_addr,
                           assignment_id=assignment_id,
                           instructor_mode=instructor_mode)
                           
@blueprint_blockpy.route('/load_assignment_give_feedback/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/load_assignment_give_feedback', methods=['GET', 'POST'])
def load_assignment_give_feedback():
    assignment_id = request.values.get('assignment_id', None)
    if assignment_id is None:
        return failure("No Assignment ID given!")
    assignment = Assignment.by_id(assignment_id)
    return jsonify(success=True, give_feedback=assignment.give_feedback)
                           
@blueprint_blockpy.route('/load_assignment/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/load_assignment', methods=['GET', 'POST'])
def load_assignment(lti=lti):
    assignment_id = request.values.get('assignment_id', None)
    group_id = request.values.get('group_id', None)
    course_id = request.values.get('course_id',  g.course.id if 'course' in g else None)
    if None in (assignment_id, course_id) or course_id == "":
        return failure("No Assignment ID or Course ID given!")
    timestamp = request.values.get('timestamp', '')
    user_id = g.user.id if g.user != None else -1
    assignment = Assignment.by_id(assignment_id)
    if user_id != -1:
        submission = assignment.get_submission(user_id, course_id=course_id)
        submission_status = submission.status
        submission_course_id = submission.course_id
        submission_code = submission.code
        log = Log.new('editor', 'load', assignment_id, user_id, 
                      body=str(assignment.version), timestamp=timestamp)
    else:
        submission_status = 0
        submission_course_id = course_id
        submission_code = assignment.starting_code or ""
    interface = ('Text' if assignment.mode.lower() == 'text' else 
                 'Split' if assignment.mode.lower() == 'split' else
                 'Upload' if assignment.mode.lower() == 'upload' else
                 'Blocks')
    upload = assignment.mode.lower() == 'upload'
    if assignment.settings:
        settings = json.loads(assignment.settings)
    else:
        settings = {}
    files = settings['files'] if 'files' in settings else []
    files = [f for f in files if f.strip()]
    added_modules = settings['modules']['added'] if 'modules' in settings else []
    removed_modules = settings['modules']['removed'] if 'modules' in settings else []
    return jsonify(success=True,
                   ip=request.remote_addr,
                   settings = {
                        'editor': interface,
                        'read_only': upload,
                        'status': submission_status
                    },
                   assignment = {
                        'assignment_id': assignment.id,
                        'course_id': course_id if course_id != None else submission_course_id,
                        'student_id': user_id,
                        'group_id': group_id,
                        'introduction': assignment.body,
                        'name': assignment.name,
                        'upload': upload,
                        'version': assignment.version,
                        'initial_view': interface,
                        'give_feedback': assignment.give_feedback,
                        'parsons': assignment.mode == 'parsons', 
                        'starting_code': assignment.starting_code,
                        'on_change': assignment.on_step,
                        'importable': settings.get('importable', False),
                        'secret': settings.get('secret', False),
                        'disable_algorithm_errors': settings.get('disable_algorithm_errors', False),
                        'disable_timeout': settings.get('disable_timeout', False),
                        'files': files,
                        'modules': {
                            'added': added_modules,
                            'removed': removed_modules,
                        },
                    },
                    programs = {
                        '__main__': submission_code,
                        'starting_code': assignment.starting_code,
                        'give_feedback': assignment.give_feedback,
                        'on_change': assignment.on_step
                    })

@blueprint_blockpy.route('/save_code/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/save_code', methods=['GET', 'POST'])
def save_code(lti=lti):
    assignment_id = request.values.get('assignment_id', None)
    assignment_version = int(request.values.get('version', -1))
    course_id = request.values.get('course_id',  g.course.id if 'course' in g else None)
    if None in (assignment_id, course_id) or course_id == "":
        return failure("No Assignment ID or Course ID given!")
    code = request.values.get('code', '')
    timestamp = request.values.get('timestamp', '')
    filename = request.values.get('filename', '__main__')
    is_version_correct = True
    if filename == "__main__":
        submission, is_version_correct = Submission.save_code(g.user.id, assignment_id, int(course_id), code, assignment_version, timestamp=timestamp)
    elif g.user.is_instructor(int(course_id)):
        if filename == "give_feedback":
            Assignment.edit(assignment_id=assignment_id, give_feedback=code)
        elif filename == "on_change":
            Assignment.edit(assignment_id=assignment_id, on_step=code)
        elif filename == "starting_code":
            Assignment.edit(assignment_id=assignment_id, starting_code=code)
        log = Log.new('instructor', filename, assignment_id, g.user.id, body=code, timestamp=timestamp)
    return jsonify(success=True, 
                   is_version_correct=is_version_correct, 
                   ip=request.remote_addr)
    
@blueprint_blockpy.route('/save_events/', methods=['GET', 'POST'])
@blueprint_blockpy.route('/save_events', methods=['GET', 'POST'])
def save_events(lti=lti):
    assignment_id = request.values.get('assignment_id', None)
    event = request.values.get('event', "blank")
    action = request.values.get('action', "missing")
    body = request.values.get('body', "")
    timestamp = request.values.get('timestamp', "")
    user_id = g.user.id if g.user != None else -1
    if assignment_id is None:
        return failure("No Assignment ID given!")
    log = Log.new(event, action, assignment_id, user_id, body=body, timestamp=timestamp)
    return jsonify(success=True, 
                   ip=request.remote_addr)
                   
def get_group_score(group_id, user_id, course_id, hide_correctness):
    group = AssignmentGroup.by_id(group_id)

templates/about.html
{% extends 'layout.html' %}

{% block title %}
BlockPy: About
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script type='text/javascript'>
</script>
{% endblock %}

{% block body %}

<h1>About</h1>

This page has public information about BlockPy and the CORGIS project.

<h2>BlockPy</h2>
<p>
<strong>BlockPy</strong> is a web-based Python environment that lets you work with blocks, text, or both. Designed for Data Science and equipped with powerful tools like the State Explorer and Guided Feedback, BlockPy lets students solve authentic, real-world problems.
</p>

<p>
The goal of BlockPy is to give you a gentle introduction to Python but eventually mature you into a more serious programming environment (such as Spyder or PyCharm). Long-term, we may support some game/animation design stuff that Scratch/Snap does, but that's not the real goal.
</p>

<p>
The BlockPy project is aimed at solving some hard technical problems: having a block-based environment for a dynamic language can be tricky - are a given pair of square brackets representing list indexing or dictionary indexing? Our goal is to use advanced program analysis techniques to provide excellent support to learners.
</p>

<p>
BlockPy owes much of its power to Google's Blockly project, the Skulpt project, Codemirror, and a host of other libraries. For a complete list, see the project GitHub.
</p>

<p>Publications related to BlockPy:
<ul>
    <li>A. C. Bart, J. Tibau, D. Kafura, E. Tilevich, C. A. Shaffer, Design and Evaluation of a Block-based Environment with a Data Science Context, IEEE Transactions on Emerging Topics in Computing '17. May, 2017.</li>
    <li>A. C. Bart, J. Tibau, E. Tilevich, C. A. Shaffer, D. Kafura, Design and Evaluation of Open-access, Data Science Programming Environment for Learners, IEEE Computer '17. May, 2017.</li>
    <li>A. C. Bart, J. Tibau, E. Tilevich, C. A. Shaffer, D. Kafura, Implementing an Open-access, Data Science Programming Environment for Learners, COMPSAC '16, Atlanta, Georgia. June 10-15, 2016.</li>
    <li>A. C. Bart, E. Tilevich, C. A. Shaffer, D. Kafura, Position Paper: From Interest to Usefulness with BlockPy, a Block-based, Educational Environment, Blocks & Beyond '15, Atlanta, Georgia. October 21-23, 2015.</li>
</ul>
</p>


<h2>CORGIS</h2>
<p>
The <strong>CORGIS project</strong> aims to transform early computer science projects by introducing real-world data via simple-to-use client libraries. Data Science offers an authentic context for your students to solve real-world problems with programming. The CORGIS project has over 40 libraries for subjects such as politics, education, literature, construction, and more!
</p>

<p>
CORGIS offers full support for Java, Python, and Racket, in addition to making its data files available in common data formats like JSON and CSV. Some datasets are also available through our unique Visualizer platform, which enables data science exploration directly within the browser!
</p>

<p>Publications related to CORGIS:
<ul>
    <li>A. C. Bart, R. Whitcomb, E. Tilevich, C. A. Shaffer, D. Kafura, Computing with CORGIS: Diverse, Real-world Datasets for. Introductory Computing (Best Research Paper), SIGCSE '17, Seattle, Washington. March, 2017.</li>
    <li>E. Tilevich, C. A. Shaffer, A. C. Bart. Creating Stimulating, Relevant, and Manageable Introductory Computer Science Projects that Utilize Real-Time, Large, Web-Based Datasets , SIGCSE'15, Kansas City, MO. 2015.</li>
    <li>E. Tilevich, C. A. Shaffer, A. C. Bart. Creating Stimulating, Relevant, and Manageable Introductory Computer Science Projects that Utilize Real-Time, Web-Based Datasets , SIGCSE'14, Atlanta, GA. 2014.</li>
    <li>A. C. Bart, J. Riddle, O. Saleem, B. Chowdhury, E. Tilevich, C. A. Shaffer, D. Kafura, Motivating Students with Big Data: CORGIS and MUSIC, Splash-E '14, Portland, Oregon. October 21-23, 2014.</li>
    <li>A. C. Bart, E. Tilevich, T. Allevato, S. Hall, C. A. Shaffer, Transforming Introductory Computer Science Projects via Real-Time Web Data, SIGCSE '14, Atlanta, Georgia. March 5-8, 2014.</li>
    <li>A. C. Bart, E. Tilevich, C. A. Shaffer, T. Allevato, S. Hall, Using Real-Time Web Data to Enrich Introductory Computer Science Projects, Splash-E '13, Indianapolis, Indiana. October 26-31, 2013.</li>
</ul>
</p>


<h2>The People Behind BlockPy and CORGIS</h2>

<table class="table table-condensed table-bordered table-striped">
    <tbody>
    
    <tr><td style="width:15%"><strong>Austin Cory Bart</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/cory.jpg') }}" alt='Photo of Austin Cory Bart'></td>
    <td>Primary Developer (CORGIS, BlockPy)<br><ul>
        <li>Status: Assistant Professor (Computer Science) at University of Delaware</li>
        <li>Email: <a href="mailto:acbart@udel.edu">acbart@udel.edu</a></li>
        <li>Website: <a href="http://www.acbart.com">www.acbart.com</a></li>
    </ul></td></tr>
    
    <tr><td style="width:15%"><strong>Luke Gusukuma</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/luke.jpg') }}" alt='Photo of Luke Gusukuma'></td>
    <td>Developer (BlockPy)<br><ul>
        <li>Status: PhD student (Computer Science) at Virginia Tech</li>
    </ul></td></tr>
    
    <tr><td style="width:15%"><strong>Javier Tibau</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/tibau.jpg') }}" alt='Photo of Javier Tibau'></td>
    <td>Developer (BlockPy)<br><ul>
        <li>Status: PhD student (Computer Science) at Virginia Tech</li>
        <li>Website: <a href="https://thirdlab.cs.vt.edu/people/javier-tibau/">https://thirdlab.cs.vt.edu/people/javier-tibau/</a></li>
    </ul></td></tr>
    
    <tr><td style="width:15%"><strong>Dennis Kafura</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/kafura.jpg') }}" alt='Photo of Dennis Kafura'></td>
    <td>Professor<br><ul>
        <li>Status: Professor (Computer Science) at Virginia Tech</li>
        <li>Email: <a href="mailto:kafura@vt.edu">kafura@vt.edu</a></li>
        <li>Website: <a href="http://people.cs.vt.edu/~kafura/">people.cs.vt.edu/~kafura/</a></li>
    </ul></td></tr>
    
    <tr><td style="width:15%"><strong>Clifford A. Shaffer</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/shaffer.jpg') }}" alt='Photo of Clifford A. Shaffer'></td>
    <td>Professor<br><ul>
        <li>Status: Professor (Computer Science) at Virginia Tech</li>
        <li>Email: <a href="mailto:shaffer@vt.edu">shaffer@vt.edu</a></li>
        <li>Website: <a href="http://people.cs.vt.edu/~shaffer/">people.cs.vt.edu/~shaffer/</a></li>
    </ul></td></tr>
    
    <tr><td style="width:15%"><strong>Eli Tilevich</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/tilevich.jpg') }}" alt='Photo of Eli Tilevich'></td>
    <td>Professor<br><ul>
        <li>Status: Associate Professor (Computer Science) at Virginia Tech</li>
        <li>Email: <a href="mailto:tilevich@vt.edu">tilevich@vt.edu</a></li>
        <li>Website: <a href="http://people.cs.vt.edu/~tilevich/">people.cs.vt.edu/~tilevich/</a></li>
    </ul></td></tr>
    
    <tr><td style="width:15%"><strong>Ryan Whitcomb</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/whitcomb.jpg') }}" alt='Photo of Ryan Whitcomb'></td>
    <td>Former Developer (CORGIS)<br><ul>
        <li>Status: Graduate of Virginia Tech</li>
    </ul></td></tr>
    
    <tr><td style="width:15%"><strong>Omar Saleem</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/omar.jpg') }}" alt='Photo of Omar Saleem'></td>
    <td>Former Developer (CORGIS)<br><ul>
        <li>Status: Graduate of Virginia Tech</li>
    </ul></td></tr>
    
    <tr><td style="width:15%"><strong>Jason Riddle</strong><br><img class="img-thumbnail img-responsive" src="{{ url_for('static', filename='images/team/jason.jpg') }}" alt='Photo of Jason Riddle'></td>
    <td>Former Developer (CORGIS)<br><ul>
        <li>Status: Graduate of Virginia Tech</li>
    </ul></td></tr>
    
</tbody></table>

<h2>VPAT</h2>

<p>If you would like to learn about BlockPy's accessibility information, you can download our <a href='{{ url_for('static', filename="resources/VPAT2.3RevINT--April2019Final-blockpy-acbart.pdf") }}' title='Link to VPAT report as a PDF'>VPAT Report</a>.
    
{% endblock %}

templates/contact.html
{% extends 'layout.html' %}

{% block title %}
BlockPy: Contact
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script type='text/javascript'>
</script>
{% endblock %}

{% block body %}

<h1>Contact</h1>

<p>
Have questions about using any of these projects? Discuss on our communities!
<ul>
<li><a href="https://groups.google.com/forum/#!forum/corgis-datasets-project" target="_blank">CORGIS Google Group</a></li>
<li><a href="https://groups.google.com/forum/#!forum/blockpy" target="_blank">BlockPy Google Group</a></li>
</ul>
</p>

<p>Want to talk to a person? Contact us below:
<ul>
<li>BlockPy or CORGIS: Austin Cory Bart (<a href="mailto:acbart@vt.edu">acbart@vt.edu</a>) </li>
</ul>
</p>

<p>
Want the code? Check out our Githubs!
<ul>
<li><a href="https://github.com/RealTimeWeb/datasets/" target="_blank">CORGIS</a></li>
<li><a href="https://github.com/RealTimeWeb/blockpy/" target="_blank">BlockPy</a></li>
<li><a href="https://github.com/acbart/blockpy-server" target="_blank">BlockPy Server</a></li>
</ul>
</p>
    
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}
BlockPy Server
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script type='text/javascript'>
</script>
{% endblock %}

{% block body %}

<h1>Main Page</h1>

<div class='row'>

<div class="media panel panel-default col-md-6 col-md-offset-3">
    <div class="media-left panel-body">
        <a href="{{ url_for('blockpy.index') }}">
            <img class="media-object" src="{{ url_for('static', filename='images/blockpy-logo-small.png')}}" alt="BlockPy">
        </a>
    </div>
    <div class="media-body panel-body">
        <h4 class="media-heading"><a href="{{ url_for('blockpy.index') }}">BlockPy</a></h4>
        BlockPy is a web-based Python environment that lets you work with blocks, text, or both. Designed for Data Science, equipped with powerful tools like the State Explorer, and scaffolding beginners with Guided Feedback, the goal of BlockPy is to let you authentically solve real-world problems.
    </div>
</div>

<div class="media panel panel-default col-md-6 col-md-offset-3">
    <div class="media-left panel-body">
        <a href="{{ url_for('corgis.index') }}">
            <img class="media-object" src="{{ url_for('static', filename='images/corgis-logo-tiny.png')}}" alt="CORGIS">
        </a>
    </div>
    <div class="media-body panel-body">
        <h4 class="media-heading"><a href="{{ url_for('corgis.index') }}">CORGIS</a></h4>
        The CORGIS Datasets Project seeks to make highly-motivating introductory computing experiences through simple, easy-to-pick-up datasets for beginners. We offer a wide range of libraries for many different programming languages and contexts.
    </div>
</div>

</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="BlockPy">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>
    <meta property="og:title" content="BlockPy" />
    <meta property="og:site_name" content="BlockPy Server"/>
    <meta property="og:url" content="{{ request.headers['Host'].split(':')[0] }}" />
    <meta property="og:description" content="Stand-alone BlockPy Server" />
    
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{{ url_for('static', filename='libs/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='libs/jquery-ui.css') }}">
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ url_for('static', filename='libs/jquery.js')}}"></script>
    <script src="{{ url_for('static', filename='libs/jquery-ui.min.js')}}"></script>
    <script src="{{ url_for('static', filename='libs/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static', filename='libs/knockout-3.4.0.js')}}"></script>
    
    <style>
    a {
        text-decoration: underline;
    }
    
    a[role="button"], button a, a.btn, .btn a, .nav a, .navbar-header a,
    .dropdown-menu a {
        text-decoration: none;
    }
    
    .navbar-inverse .navbar-nav>li>a {
        color: white;
    }
    
    .navbar-inverse a.navbar-brand {
        color: white;
    }
    
    .navbar-inverse .navbar-link.btn.btn-default {
        color: black;
    }
    
    .nav a.dropdown-toggle:focus {
        outline: 1px solid rgb(77, 144, 254);
    }
    
    table caption {
        color: #333;
    }
    
    .label-default {
        background-color: #444;
    }
    
    </style>
    
    <style>
    {% block extracss %}
    {% endblock %}
    </style>
    
    {% block extrahead %}
    {% endblock %}
    
    <script type="text/javascript">
    {% block extrajs %}
    {% endblock %}
    
    {% if not reduced_layout %}
    $(document).ready(function () {
        $("#{{request.endpoint|replace('.', '\\\\.')}}").parent().addClass("active");
        setTimeout(function() {
            $("#survey-link").tooltip('show');
        }, 5000);
    });
    {% endif %}
    </script>
    
    
  </head>
<body>

{% if not reduced_layout %}
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('index') }}">
        <img alt="BlockPy Brand"
             role='presentation'
             src="{{ url_for('static', filename='images/puppy-corgi-head.png')}}">
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('index') }}">BlockPy</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a id='index' href="{{ url_for('index') }}">Home</a></li>
        {% if g.user %}
        <li><a id='courses.index' href="{{ url_for('courses.index') }}">Courses</a></li>
        {% endif %}
        <li class="dropdown" tabindex="-1">
            <a href="#" class="dropdown-toggle"
               data-toggle="dropdown" role="button"
               aria-haspopup="true" aria-expanded="false"
               >Tools <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="{{ url_for('blockpy.index') }}">BlockPy</a></li>
                <li><a href="{{ url_for('corgis.index') }}">CORGIS Datasets</a></li>
            </ul>
        </li>
        {% if g.user and g.user.is_admin() %}
        <li><a href="{{ url_for('admin.index') }}">Admin</a></li>
        {% endif %}
        <li><a id='about' href="{{ url_for('about') }}">About</a></li>
        <li><a id='contact' href="{{ url_for('contact') }}">Contact</a></li>
      </ul>
      {% if g.user %}
      <p class="navbar-text navbar-right">Signed in as {{ g.user.name() }} <a href="{{ url_for('security.logout') }}" class="navbar-link">(log out)</a></p>
      {% else %}
      <p class="navbar-right navbar-btn">
      <a class="navbar-link btn btn-default" href="{{ url_for('security.login') }}">Log in</a>
      <a class="navbar-link btn btn-default" href="{{ url_for('security.register') }}">Register</a>
      </p>
      {% endif %}
    </div><!--/.nav-collapse -->
  </div>
</nav>
{% endif %}

{% with messages = get_flashed_messages() %}
  <script>
  {% for message in messages %}
      console.error("Flask Message:", {{ message|tojson }});
  {% endfor %}
  </script>
{% endwith %}

<div class="container" role='main'>
{% block body %}
{% endblock %}
</div>

<!-- begin footer -->
<hr/>
  <footer class="footer" style="margin-top:20px;">
    <div class="container">
      <p class="pull-right">
        {% if g.user %}
          <span>{{ g.user.email}}</span> | <a href="#">Back to top</a>
        {% else %}
          <span>Not logged in</span> | <a href="#">Back to top</a>
        {% endif %}
      </p>
      <p>
        &copy; Copyright 2019 <a href="https://acbart.com">Austin Cory Bart</a>, Luke Gusukuma, Dennis Kafura.
      </p>
    </div>
  </footer>
<!-- end footer -->
    
</body>

</html>