controllers/courses.py
from pprint import pprint
from collections import defaultdict
from natsort import natsorted

from flask_wtf import Form
from wtforms import IntegerField, BooleanField, TextField, SubmitField, SelectField

from flask import Blueprint, send_from_directory
from flask import Flask, redirect, url_for, session, request, jsonify, g,\
                  make_response, Response, render_template, flash
from werkzeug.utils import secure_filename
                  
from sqlalchemy import Date, cast, func, desc, or_

from controllers.helpers import instructor_required, login_required, get_course_id

from main import app
from models.models import db, Assignment, AssignmentGroup, Course, User, Role, Submission

courses = Blueprint('courses', __name__, url_prefix='/courses')

class AddCourseForm(Form):
    name = TextField("Name")
    visibility = SelectField(u'Visibility', choices=[('private', 'Private'), ('public', 'Public')])
    submit = SubmitField("Add new course")

@courses.route('/add/', methods=['GET', 'POST'])
@courses.route('/add', methods=['GET', 'POST'])
@instructor_required
def add():
    """ Create a new assignment with the given information
    """
    add_form = AddCourseForm(request.form)
    if request.method == 'POST':
        Course.new(name=add_form.name.data,
                   owner_id = g.user.id,
                   visibility=add_form.visibility.data)
        flash('New course added')
        return redirect(url_for('courses.index'))
    return render_template('courses/add.html', add_form=add_form)
    
@courses.route('/remove/', methods=['GET', 'POST'])
@courses.route('/remove', methods=['GET', 'POST'])
@get_course_id
def remove_course(course_id):
    Course.remove(course_id)
    return jsonify(success=True)
        
@courses.route('/rename/', methods=['GET', 'POST'])
@courses.route('/rename', methods=['GET', 'POST'])
@get_course_id
def rename_course(course_id):
    new_name = request.values.get('name', "Untitled Course")
    Course.rename(course_id, new_name)
    return jsonify(success=True)
    
@courses.route('/add_canvas/', methods=['GET', 'POST'])
@courses.route('/add_canvas', methods=['GET', 'POST'])
@login_required
def add_canvas():
    """
    Create a new assignment with the given information
    """
    return render_template('courses/add_canvas.html')
    
@courses.route('/<course_id>/', methods=['GET', 'POST'])
@courses.route('/<course_id>', methods=['GET', 'POST'])
@login_required
def course(course_id):
    course = Course.query.filter_by(id=course_id).first()
    if course is None:
        return "Course not found!"
    assignments = (db.session.query(Assignment)
                             .filter(Assignment.course_id==course.id)
                             .all())
    is_instructor = g.user.is_instructor(int(course_id))
    return render_template('courses/course.html', 
                           course=course,
                           is_instructor=is_instructor,
                           assignments=assignments)
                           
@courses.route('/assignments/<course_id>/', methods=['GET', 'POST'])
@courses.route('/assignments/<course_id>', methods=['GET', 'POST'])
@login_required
def assignments(course_id):
    #TODO: ensure in course
    assignments = Assignment.get_available()
    groups = AssignmentGroup.query.all()
    course_groups = Course.get_all_groups()
    editable_courses = g.user.get_editable_courses()
    
    return render_template('courses/assignments.html', assignments=assignments, groups=groups, editable_courses=editable_courses, course_groups=course_groups, course_id=course_id)

@courses.route('/view_assignments/<course_id>/', methods=['GET', 'POST'])
@courses.route('/view_assignments/<course_id>', methods=['GET', 'POST'])
@login_required
def view_assignments(course_id):
    #TODO: ensure in course
    course = Course.by_id(course_id)
    assignments = Assignment.by_course(course_id)
    groups = AssignmentGroup.by_course(course_id)
    
    return render_template('courses/view_assignments.html', assignments=assignments, groups=groups, course=course, course_id=course_id)

@courses.route('/', methods=['GET', 'POST'])
@login_required
def index():
    """
    List all of the courses associated with the user.
    """
    
    user_id = g.user.id
    
    my_courses = g.user.get_courses()
    public_courses = Course.get_public()
    
    return render_template('courses/index.html', my_courses=my_courses,
                                                 public_courses=public_courses)
    
@courses.route('/manage_users/<course_id>/', methods=['GET', 'POST'])
@courses.route('/manage_users/<course_id>', methods=['GET', 'POST'])
@login_required
def manage_users(course_id):
    ''' List all the users in the course '''
    is_instructor = g.user.is_instructor(int(course_id))
    students = Course.by_id(int(course_id)).get_users()
    return render_template('courses/manage_users.html',
                           students=students,
                           course_id=course_id,
                           is_instructor=is_instructor)

class AddStudentForm(Form):
    invite = BooleanField("Add Without Invitation")
    send_email = BooleanField('Send Email')
    # TODO: Multiline textbox
    new_users = TextField("Emails")
    submit = SubmitField("Add student")
                                                 
@courses.route('/add_users/<course_id>/', methods=['GET', 'POST'])
@courses.route('/add_users/<course_id>', methods=['GET', 'POST'])
@login_required
def add_users(course_id):
    ''' Generate a form to add a student '''
    add_form = AddStudentForm(request.form)
    if request.method == 'POST':
        for new_email in add_form.new_users.data.split("\n"):
            new_user = User.find_student(email=new_email)
            if new_user is None:
                new_user = User.new_from_instructor(email=new_email)
            if not new_user.is_student():
                new_user.add_role('learner', course_id=course_id)
            # TODO: Send an email
        flash('New students added')
        return redirect(url_for('courses.manage_users', course_id=course_id))
    return render_template('courses/add_users.html', add_form=add_form, course_id=course_id)
    
@courses.route('/remove_role/<role_id>/', methods=['GET', 'POST'])
@courses.route('/remove_role/<role_id>', methods=['GET', 'POST'])
@login_required
def remove_role(role_id):
    ''' Endpoint to bounce a student from the course '''
    role = Role.by_id(int(role_id))
    if role is None:
        return "Role not found"
    course_id = role.course_id
    is_instructor = g.user.is_instructor(course_id)
    if not is_instructor:
        return "You're not an instructor in this course!"
    Role.remove(int(role_id))
    return redirect(url_for('courses.manage_users', course_id=course_id))
    
@courses.route('/change_role/', methods=['GET', 'POST'])
@courses.route('/change_role', methods=['GET', 'POST'])
@login_required
def change_role():
    ''' Endpoint to change the role of a student '''
    pass

@courses.route('dashboard/', methods=['GET', 'POST'])
@courses.route('dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    return redirect(url_for('utilities.dashboard'))

                           
@courses.route('/config/', methods=['GET', 'POST'])
@courses.route('/config', methods=['GET', 'POST'])
def config():
    """ Create a new assignment with the given information
    """
    return Response(render_template('courses/config.xml',
                                    version='1'), mimetype='text/xml')
                                    
@courses.route('/submissions_filter/<course_id>/', methods=['GET', 'POST'])
@courses.route('/submissions_filter/<course_id>', methods=['GET', 'POST'])
@login_required
def submissions_filter(course_id):
    ''' List all the users in the course '''
    is_grader = g.user.is_grader(int(course_id))
    if not is_grader:
        return "You are not an instructor or TA in this course!"
    course_id = int(course_id)
    course = Course.by_id(course_id)
    students = natsorted(course.get_students(), key=lambda r: r.name())
    assignments = natsorted([a for a, m in course.get_submitted_assignments()],
                            key=lambda r: r.name)
    criteria = request.values.get("criteria", "none")
    search_key = int(request.values.get("search_key", "-1"))
    submissions = []
    if criteria == "student":
        all_subs = Submission.by_student(search_key, course_id)
        all_subs = {s[0].assignment_id: s for s in all_subs}
        submissions = [all_subs.get(assignment.id, (None, None, assignment))
                       for assignment in assignments]
    elif criteria == "assignment":
        all_subs = Submission.by_assignment(search_key, course_id)
        all_subs = {s[0].user_id: s for s in all_subs}
        submissions = [all_subs.get(student.id, (None, student, None))
                       for student in students]
    return render_template('courses/submissions_filter.html',
                           course_id=course_id,
                           assignments=assignments,
                           students=students,
                           submissions= submissions,
                           criteria = criteria,
                           search_key = search_key,
                           is_instructor=is_grader)
@courses.route('/submissions_specific/<submission_id>/', methods=['GET', 'POST'])
@courses.route('/submissions_specific/<submission_id>', methods=['GET', 'POST'])
@login_required
def submissions_specific(submission_id):
    ''' List all the users in the course '''
    submission, user, assignment = Submission.full_by_id(int(submission_id))
    if submission is None:
        return "Submission not found"
    course_id = submission.course_id
    if course_id is not None:
        is_instructor = g.user.is_instructor(int(course_id))
    else:
        is_instructor = False
    is_owner = g.user.id == submission.user_id

templates/courses/add.html
{% from "helpers/_formhelpers.html" import render_field %}
{% extends 'layout.html' %}

{% block title %}
Courses: Index
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script type='text/javascript'>
</script>
{% endblock %}

{% block body %}

<h1>Add New Non-LMS Course</h1>

<form method=post action="{{ url_for('courses.add') }}">
  <dl>
    {{ render_field(add_form.name) }}
    {{ render_field(add_form.visibility) }}
  </dl>
  <p><input type=submit value=Register>
</form>

{% endblock %}

templates/courses/add_canvas.html
{% extends 'layout.html' %}

{% block title %}
Courses: Add Canvas Course
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script type='text/javascript'>
</script>
{% endblock %}

{% block body %}


<h1>Add Canvas Course</h1>

<a href="{{ url_for('courses.index') }}">Back to all courses</a>

<div>
To add our tools to your Canvas course, you'll need to do the following.

{% set pylti_config = config['PYLTI_CONFIG']['consumers'].items()|list %}

<ol>
    <li>Create and visit your course on Canvas.</li>
    <li>Go to "Settings" on the left sidebar menu.</li>
    <li>Go to the "Apps" tab.</li>
    <li>Click "View App Configurations".</li>
    <li>Click "Add App".</li>
    <li>Choose "Paste XML".</li>
    <li>For the name, enter <code>BlockPy Version {{ config['SITE_VERSION'] }}</code></li>
    <li>For the Consumer Key, enter <code>{{ pylti_config[0][0] }}</code></li>
    <li>For the Shared Secret, enter <code>{{ pylti_config[0][1]['secret'] }}</code></li>
    <li>For the XML Configuration, copy the XML on the following page: <a href="{{ url_for('courses.config') }}">LTI XML Configuration</a></li>
    <li>To add new BlockPy/Maze assignments, choose the "External Tool" type and select "BlockPy Version {{ config['SITE_VERSION'] }}" from the list.</li>
</ol>

</div>

{% endblock %}

templates/courses/add_users.html
{% from "helpers/_formhelpers.html" import render_field %}
{% extends 'layout.html' %}

{% block title %}
Courses: Add Users
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script type='text/javascript'>
</script>
{% endblock %}

{% block body %}

<form method=post action="{{ url_for('courses.add_users', course_id=course_id) }}">
  <dl>
    {{ render_field(add_form.invite) }}
    {{ render_field(add_form.send_email) }}
    <p>Add each new user email on a new line. Optionally, you can include their names ("First Name|Last Name|email@email.com").</p>
    {{ render_field(add_form.new_users) }}
  </dl>
  <p><input type=submit value="Add Student">
</form>

{% endblock %}

templates/courses/course.html
{% extends 'layout.html' %}

{% block title %}
Courses: {{ course.name }}
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script src='{{ url_for("static", filename="libs/knockout-3.4.0.js")}}'></script>
<script type='text/javascript'>

function renameCourse() {
    new_name = window.prompt("Give a new name for this course:", {{ course.name|tojson }});
    if (new_name != null) {
        window.location.href = {{ url_for('courses.rename_course', course_id=course.id)|tojson }}+"&name="+new_name;
    }
}

$().ready(function() {
    var mainModel = {
        'courses': ko.observableArray([])
    };
});

</script>
{% endblock %}

{% block body %}

<h1>Courses: {{ course.name }}</h1>

<a href="{{ url_for('courses.index') }}">Back to all courses</a>

{% if is_instructor %}
<h3>Manage Assignments</h3>
<a href="{{ url_for('courses.assignments', course_id=course.id) }}" class='btn btn-default'>Manage Assignments</a><br><br>
{% else %}
<h3>View Assignments</h3>
{% endif %}

<a href="{{ url_for('courses.view_assignments', course_id=course.id) }}" class='btn btn-default'>View Assignments</a><br><br>

{% if is_instructor %}

<a href="{{ url_for('courses.manage_users', course_id=course.id) }}" class='btn btn-default'>Manage Students</a>

<h3>Submissions</h3>

<a href="{{ url_for('courses.submissions_filter', course_id=course.id) }}" class='btn btn-default'>Filter Submissions</a><br><br>

<a href="{{ url_for('courses.submissions_grid', course_id=course.id) }}" class='btn btn-default'>Submissions Grid</a><br><br>

<h3>Edit Course</h3>        

<a href="{{ url_for('courses.remove_course', course_id=course.id) }}" onclick="return confirm('Are you sure?')" class='btn btn-danger'>Delete Course</a><br><br>
<button onclick="renameCourse()" class='btn btn-default'>Rename Course</button><br>

{% endif %}

{% endblock %}

templates/courses/index.html
{% extends 'layout.html' %}

{% block title %}
Courses: Index
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}
<script src='{{ url_for("static", filename="libs/knockout-3.4.0.js")}}'></script>
<script type='text/javascript'>

$().ready(function() {
    mainModel = {
        'my_courses': ko.observableArray([]),
        'public_courses': ko.observableArray([]),
    };
    {% for course, role in my_courses %}
    mainModel.my_courses.push({
        'id': ko.observable({{ course.id|tojson}}),
        'name': ko.observable({{ course.name|tojson}}),
        'service': ko.observable({{ course.service|tojson}}),
        'role': ko.observable({{ role.name|title|tojson }}),
        'url': ko.observable({{ url_for('courses.course', course_id=course.id)|tojson}}),
        'created': ko.observable({{ course.date_created|tojson }}),
        'sort_date': ko.observable({{ (course.date_created.strftime('%Y/%m'))|tojson }}),
        'display_date': ko.observable({{ (course.date_created.strftime('%b %Y'))|tojson }})
    })
    {% endfor %}
    
    mainModel.my_courses.sort(function(left, right) {
        return left.sort_date() === right.sort_date() ? 0
             : left.sort_date() < right.sort_date() ? -1
             : 1;
    });
    
    {% for course in public_courses %}
    mainModel.public_courses.push({
        'id': ko.observable({{ course.id|tojson}}),
        'name': ko.observable({{ course.name|tojson}}),
        'service': ko.observable({{ course.service|tojson}}),
        'url': ko.observable({{ url_for('courses.course', course_id=course.id)|tojson}})
    })
    {% endfor %}
    
    ko.applyBindings(mainModel);
});

</script>
{% endblock %}

{% block body %}

<h1>Courses</h1>

<h3>Create</h3>

<a href="{{ url_for('courses.add') }}" class='btn btn-default'>Create new course</a><br>
<a href="{{ url_for('courses.add_canvas') }}" class='btn btn-default'>Create new Canvas course</a>
<br><br>
Want to make <strong><a href="{{ url_for('courses.making_problems') }}">new BlockPy assignments?</a></strong>

<h3>My Courses</h3>

You are enrolled in the following courses:

<ul data-bind="foreach: my_courses">
    <li>
        <a data-bind="attr: {href: url}">
            <strong data-bind="text: name()"></strong>:
        </a>
        <span data-bind="text: role"></span>
        (<span data-bind="text: display_date"></span>)
    </li>
</ul>

<h3> Public Courses</h3>

The following courses are available for you

<ul data-bind="foreach: public_courses">
    <li>
        <a data-bind="attr: {href: url}">
            <b data-bind="text: name()"></b>
        </a>
    </li>
</ul>

{% endblock %}

templates/courses/manage_users.html
{% extends 'layout.html' %}

{% block title %}
Courses: Students
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}

<script type='text/javascript'>

function MainModel() {
    var self = this;
}
mainModel = new MainModel();
$().ready(function() {
    ko.applyBindings(mainModel);
});


</script>
{% endblock %}

{% block body %}

<h1>Manage Students</h1>

<p>Back to <a href="{{ url_for('courses.course', course_id=course_id) }}">Course</a></p>

<a href="{{ url_for('courses.add_users', course_id=course_id) }}" class='btn btn-default'>Add Students</a><br>

<table class="table table-condensed table-hover">
<caption>All users in course:</caption>
<tbody>
<tr>
    <th>Name</th>
    <th>Email</th>
    <th>Roles</th>
    <th>Remove</th>
</tr>
{% for role, student in students %}
<tr>
    <td>{{ student.last_name }}, {{ student.first_name}}</td>
    <td>{{ student.email }}</td>
    <td>{{ role.name }}</td>
    <td><a href="{{ url_for('courses.remove_role', role_id=role.id) }}" onclick="return confirm('Are you sure?')" class='btn btn-danger'>Remove</a><br><br></td>
<tr>
{% endfor %}
</tbody>
</table>


{% endblock %}

templates/courses/submissions_filter.html
{% extends 'layout.html' %}

{% block title %}
Courses: Submissions Filter
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}

<script type='text/javascript'>

function MainModel() {
    var self = this;
}
mainModel = new MainModel();
$().ready(function() {
    ko.applyBindings(mainModel);
    
    $("#search-assignments").change(function(i, v) {
        if (i.target.value != "") {
            window.location.href = {{ url_for('courses.submissions_filter', course_id=course_id)|tojson }}+"?criteria=assignment&search_key="+i.target.value;
        }
    });
    
    $("#search-students").change(function(i, v) {
        if (i.target.value != "") {
            window.location.href = {{ url_for('courses.submissions_filter', course_id=course_id)|tojson }}+"?criteria=student&search_key="+i.target.value;
        }
    });
});


</script>
{% endblock %}

{% block body %}

<h1>Submission Filter</h1>

<p>Back to <a href="{{ url_for('courses.course', course_id=course_id) }}">Course</a></p>

<label>Student:
<select id='search-students'>
<option value=''></option>
{% for student in students %}
<option value='{{ student.id }}'
{%- if criteria == "student" and search_key == student.id %} selected 
{%- endif %} >{{ student.last_name}}, {{ student.first_name }}</option>
{% endfor %}
</select>
</label>
<br><br>

<label>Assignment:
<select id='search-assignments'>
<option value=''></option>
{% for assignment in assignments %}
<option value='{{ assignment.id }}'
{%- if criteria == "assignment" and search_key == assignment.id %} selected 
{%- endif %} >{{ assignment.title() }}</option>
{% endfor %}
</select>
</label>
<br><br>

<table class="table table-condensed table-hover table-striped table-bordered">
<caption>Student's submissions for course's assignments.</caption>
<tbody>
<tr>
    {% if criteria=="student" %}<th>Assignment</th>{%endif %}
    {% if criteria=="assignment" %}<th>Student</th>{%endif %}
    <th>Correct</th>
    <th>Status</th>
    <th>View</th>
    <th>Touches</th>
</tr>
{% for submission in submissions %}
<tr class='{% if submission[0].correct%}success{% endif %}'>
    {% if criteria=="student" %}<td>{{ submission[2].title() }}</td>{%endif %}
    {% if criteria=="assignment" %}<td>{{ submission[1].name() }}</td>{%endif %}
    <td>{% if submission[0].correct%}Yes{% else %}No{% endif %}</td>
    <td>{{ submission[0].status }}</td>
    <td>{% if submission[0] != None -%}
    <a href="{{ url_for('courses.submissions_specific', submission_id=submission[0].id) }}">View</a>{% endif %}</td>
    <td>{{ submission[0].version or "0"}}</td>
</tr>
{% endfor %}
</tbody>
</table>


{% endblock %}

templates/courses/submissions_grid.html
{% extends 'layout.html' %}

{% block title %}
Courses: Submissions Grid
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}

<script type='text/javascript'>

function MainModel() {
    var self = this;
}
mainModel = new MainModel();
$().ready(function() {
    ko.applyBindings(mainModel);
});


</script>
{% endblock %}

{% block body %}

<h3>Submission Grid</h3>

<p>Back to <a href="{{ url_for('courses.course', course_id=course_id) }}">Course</a></p>

<div style='overflow-x: auto'>

<table class="table table-condensed table-hover table-striped table-bordered">
<tbody>

<!-- Group Header -->
<tr>
    <th></th>
    {% for group in assignment_groups %}
    {% set colspan = grouped_assignments[group.id]|length %}
    {% if colspan > 0 %}
    <th colspan="{{ colspan }}">{{ group.name}}</th>
    {% endif %}
    {% endfor %}
</tr>

<!-- Assignments -->
<tr>
    <th></th>
    {% for group in assignment_groups %}
    {% for assignment in grouped_assignments[group.id] %}
    <th>{{ assignment.title()}}</th>
    {% endfor %}
    {% endfor %}
</tr>

<!-- Student Submissions -->
{% for student in students %}
<tr>
    <td>{{ student.name() }}</td>
    {% for group in assignment_groups %}
    {% for assignment in grouped_assignments[group.id] %}
    <td>
    {% if (assignment.id, student.id) in submissions %}
    <a href="{{ url_for('courses.submissions_specific', 
                submission_id=submissions[(assignment.id, student.id)].id) }}">
    <img src="{{ url_for('static', 
                 filename='images/'+
                 ('tick.png' if submissions[(assignment.id, student.id)].correct else 'text_italic.png')) }}">
    </a>
    {% else %}
    <img src="{{ url_for('static', filename='images/red-x.png') }}">
    {% endif %}
    </td>
    {% endfor %}
    {% endfor %}
</tr>
{% endfor %}

</tbody>
</table>

</div>


{% endblock %}

templates/courses/submissions_specific.html
{% extends 'layout.html' %}

{% block title %}
Courses: View Submission
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}

<script type='text/javascript'>

function MainModel() {
    var self = this;
}
mainModel = new MainModel();
$().ready(function() {
    ko.applyBindings(mainModel);
});


</script>
{% endblock %}

{% block body %}

<h3>View Submission<br><small>Back to <a href="{{ url_for('courses.course', course_id=course_id if course_id != None else 0) }}">Course</a></small></h3>


{{ assignment.title() }} (<a href="{{ url_for('assignments.load', assignment_id=assignment.id) }}">View</a>)<br>
{{ assignment.body|safe}}<br>

<h4>Submission</h4>
Submitter: {{ user.name() }} ({{ user.email }})<br>
Completed: {{ submission.correct }}<br>
Status: {{ submission.status }}<br>
Touches: {{ submission.version }}<br>
Started: {{ submission.date_created.strftime("%B %d %Y, %I:%M %p") }}<br>
Last Change: {{ submission.date_modified.strftime("%B %d %Y, %I:%M %p") }}<br>
{% if assignment.type == "blockpy" %}

Code: {% filter highlight_python_code(True) -%}
{{ submission.code|safe }}
{% endfilter %}<br>
{% elif assignment.type == "explain" %}
Response: <pre>{{ (submission.code|json_load).code }}</pre>
<ol>
{% for element in (submission.code|json_load).elements.values() %}
{% if element.present %}
<li>{{ element.name }} ({{ element.line }}): {{ element.answer }}</li>
{% endif %}
{% endfor %}
</ol>
{% endif %}
<span id='blocks-tag'>Blocks: <img src="{{ url_for('blockpy.get_submission_image', submission_id=submission.id, course_id=course_id, _external=True) }}" onerror="document.getElementById('blocks-tag').innerHTML='No blocks submitted'" ></span><br>

{% endblock %}

templates/courses/view_assignments.html
{% extends 'layout.html' %}

{% block title %}
Courses: Assignments
{% endblock %}

{% block statusbar %}
{% endblock %}

{% block extrahead %}

<script type='text/javascript'>

function MainModel() {
    var self = this;
}
mainModel = new MainModel();
$().ready(function() {
    ko.applyBindings(mainModel);
});


</script>
<style>
.btn-group {
    display: flex;
}

.table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
    background-color: #e9eaed;
}

tr:hover.hover-movers-rows div.mover-buttons {
    visibility: visible;
}

tr.hover-movers-rows div.mover-buttons {
    visibility: hidden;
}

tr:hover.hover-remove-rows button.remove-button {
    visibility: visible;
}

tr.hover-remove-rows button.remove-button {
    visibility: hidden;
}

</style>
{% endblock %}

{% block body %}

<h1>Assignments</h1>

{% for group in groups %}

{% endfor %}


<table class="table table-condensed table-hover">
<tbody>
    
    {% for group in groups %}
    
    
    <tr class="active hover-remove-rows">
        <td class="col-md-12 col-sm-12 col-xs-12" colspan="3">
            <strong>{{ group.name }}</strong>
        </td>
    </tr>
    
    {% for assignment in group.get_assignments() %}
    
    <tr class='hover-movers-rows'>
        <td class='col-md-5 col-sm-5 col-xs-5'>
            <a href="{{ url_for('assignments.load', assignment_id=assignment.id, course_id=course_id) }}"><strong>{{ assignment.title() }}</strong></a><br>
            Last modified at
            <span>{{ assignment.modified }}</span>
        </td>
        <td class='col-md-7 col-sm-7 col-xs-7'>
            <span class='label label-default'>{{ assignment.type }}</span>
            <span>{{ assignment.body|safe }}</span>
        </td>
    </tr>
    
    {% endfor %}
    
    {% endfor %}
    
</tbody>
</table>


{% endblock %}